### Reading Files in Pandas

### Import the necessary libraries

In [2]:
import pandas as pd

### Load the csv file from this <a href = "https://raw.githubusercontent.com/Prajwalk09/Data-Analysis-with-Pandas-and-Python/refs/heads/main/Series/google_stock_price.csv">link</a> into a variable called `stock_data` as a Series

In [4]:
stock_data = pd.read_csv('https://raw.githubusercontent.com/Prajwalk09/Data-Analysis-with-Pandas-and-Python/refs/heads/main/Series/google_stock_price.csv')

### Load another csv file from this <a href= "https://raw.githubusercontent.com/Prajwalk09/Data-Analysis-with-Pandas-and-Python/refs/heads/main/Series/pokemon.csv">link</a> into a varaible called `pokemon_data`. Use only the *Pokemon* column and store the result as a Series

In [5]:
pokemon_data = pd.read_csv('https://raw.githubusercontent.com/Prajwalk09/Data-Analysis-with-Pandas-and-Python/refs/heads/main/Series/pokemon.csv')

### Display the first 5 rows from both the variables

In [6]:
stock_data.head()

   Stock Price
0        50.12
1        54.10
2        54.65
3        52.38
4        52.95

In [7]:
pokemon_data.head()

      Pokemon   Type
0   Bulbasaur  Grass
1     Ivysaur  Grass
2    Venusaur  Grass
3  Charmander   Fire
4  Charmeleon   Fire

### Display the length of the `pokemon_data` variable

In [10]:
len(pokemon_data)

721

### Use the `min()` and `max()` functions on `stock_data` and `pokemon_data`

<span style="font-size:14px; color:blue;">What conclusions can you make about the behavior of `min()` and `max()` when applied to non-numeric data?</span>

In [11]:
min(pokemon_data)

'Pokemon'

In [12]:
max(pokemon_data)

'Type'

In [13]:
min(stock_data)

'Stock Price'

In [15]:
max(stock_data)

# min and max on non numeric display the first thing they find ig

'Stock Price'

### Sort the values in the `pokemon_data` in ascending order and the values in `stock_data` in descending order

In [31]:
pokemon_data = pokemon_data.sort_values(by="Pokemon", ascending=True)
pokemon_data.head()

       Pokemon     Type
459  Abomasnow    Grass
62        Abra  Psychic
358      Absol     Dark
616   Accelgor      Bug
680  Aegislash    Steel

In [32]:
stock_data = stock_data.sort_values(by="Stock Price", ascending = False)
stock_data.head()

      Stock Price
3011       782.22
2859       776.60
3009       773.18
3007       772.88
3010       771.61

### Extract the 5th value from the `pokemon_data` Series

In [34]:
pokemon_data.iloc[5]

Pokemon    Aerodactyl
Type             Rock
Name: 141, dtype: object

### Extract the 10th, 15th and 20th value from the `pokemon_data` Series

In [36]:
pokemon_data.iloc[[10,15,20]]

      Pokemon    Type
333   Altaria  Dragon
346   Anorith    Rock
566  Archeops    Rock

### Extract all the values between the 10th and 20th index in the `pokemon_data` Series

In [37]:
pokemon_data.iloc[range(10,20)]

       Pokemon      Type
333    Altaria    Dragon
697     Amaura      Rock
423    Ambipom    Normal
590  Amoonguss     Grass
180   Ampharos  Electric
346    Anorith      Rock
23       Arbok    Poison
58    Arcanine      Fire
492     Arceus    Normal
565     Archen      Rock